service: step-function

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-3
  profile: default

  iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "states:ListStateMachines"
      - "states:StartExecution"
    Resource: "arn:aws:states:*:*:*"

functions:
  executeStepFunction:
    handler: handler.executeStepFunction
    events:
      - http:
          path: run
          method: get
  inputValidation:
    handler: handler.inputValidation
  getCar:
    handler: handler.getCar
  removeCar:
    handler: handler.removeCar
  addCar:
    handler: handler.addCar
  getCars:
    handler: handler.getCars


stepFunctions:
  stateMachines:
    testingStateMachine:
      name: TestingStateMachine
      definition:
        StartAt: InputValidation
        States:
          InputValidation:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-inputValidation
            Next: GetCar
          GetCar:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-getCar
            Next: ProcessOperation
          ProcessOperation:
            Type: Choice
            Choices : 
              - Variable: "$.operationType"
                StringEquals: "ADD"
                Next: AddCar
              - Variable: "$.operationType"
                StringEquals: "REMOVE"
                Next: RemoveCar
          AddCar:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-addCar
            Next: GetAllCars
          RemoveCar:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-removeCar
            Next: GetAllCars
          GetAllCars:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-getCars
            End: true
